### ISSUE TITLE
How to search for current word under cursor?

### ISSUE THREAD

**Issue by hoschi** [brooth/far.vim#12]
I tried `:F <cword> .` but it gives me zero matches. When I type the word it works as expected.

**Comment by brooth** [comment]
Why don't you use `<c-r><c-w>` shortcut? I'm also not sure that this feature is any useful. Do you know any others plugins or built-in commands with such behavior?

**Comment by hoschi** [comment]
didn't know about `<c-r><c-w>`, this totally fixes my issue. `<cword>` is some built in thing and I just wondered why it didn't work ;) see `:help cword` in vim. I use it with other plugins to define commands which define all parameters, for Far it could be something like `nmap <Leader>ff :F <cword> [^test].js<cr>` to search for current word under cursor in all JS files but excluding tests. Here are some examples for Ack plugin:
```
autocmd FileType javascript
	\  nmap <buffer> <LocalLeader>sw :Ack --js<space>
	\| nmap <buffer> <LocalLeader>sc :Ack --js <cword><cr>
	\| nmap <buffer> <LocalLeader>sf :Ack! --js FIXME <cr>
	\| nmap <buffer> <LocalLeader>st :Ack! --js TODO <cr>
```

**Comment by hoschi** [comment]
If you want to support <cword> you can reopen the issue and I will test it when another beta comes out ;) For now I go with your shortcut.

**Comment by dnyaneshgate** [comment]
This worked for me.
`nnoremap <silent> <leader>f :execute 'F '.expand('<cword>').' .'<CR>`
