### ISSUE TITLE
let g:far#source = 'agnvim' doesn't work

### ISSUE THREAD

**Issue by ronakg** [brooth/far.vim#18]
I'm running neovim and ag is installed. When `g:far#source` is set to `agnvim` the search always returns 0 returns.

Any ideas?

**Comment by brooth** [comment]
Sure, ag doesn't understand wildcards, but regexp. So use `\.js` instead of `**/*.js` e.g. I'm going to write this down in help soon..

**Comment by ronakg** [comment]
Thanks. How to search through all files instead of particular extension? What's equivalent of `**/*`?

**Comment by brooth** [comment]
Just use dot (`.`). This means any symbols in the path.
