### ISSUE TITLE
"No matching buffer" when running Fardo

### ISSUE THREAD

**Issue by tmccombs** [brooth/far.vim#19]
I am using Far in nvim with agnvim as the source.

When I run `Fardo` I get the following error:

```
line 41:         if !empty(cmds)
line 42:             let buf_repls = 0
line 43:             let cmds = reverse(cmds)
line 44: 
line 45:             exec 'buffer! '.file_ctx.fname
line 45: buffer! user-service/conf/application.conf
Error detected while processing function FarDo[2]..far#replace:
line   45:
E94: No matching buffer for user-service/conf/application.conf
function FarDo[2]..far#replace returning #-1
continuing in function FarDo
function FarDo returning #-1
```

It looks like Fardo does succesffully replace for a single file, but I have to run Fardo for every file, and get this error (or something like it) every time.

**Comment by brooth** [comment]
That's weird. Do you have any buffer-related tweaks or plugins in your vimrc?

**Comment by tmccombs** [comment]
I get the same error with a vim config with nothing but add Far directory to my runtimepath.

nvim is version 0.1.7.

**Comment by brooth** [comment]
Linux shouldn't be the problem. I also use nvim 0.1.7 running on Ubuntu 16.04.

Could you check something on your side please. Modify `autoload/far.vim`, add absolute path to the `user-service` dir, i.e. instead of this (~ line 816):

```
    exec 'buffer! '.file_ctx.fname
```
should be this:
```
    exec 'buffer! <PATH TO "user-service" DIR>/'.file_ctx.fname
```

**Comment by tmccombs** [comment]
Same problem.

**Comment by brooth** [comment]
Do you mean `ls!` shows all the open buffers but after `Fardo` there is only current one left?

**Comment by brooth** [comment]
Can you try again with these options:
```
g:far#auto_write_replaced_buffers = 0
g:far#auto_delete_replaced_buffers = 0
```

**Comment by tmccombs** [comment]
I still get the error with those options (I tried both)

**Comment by tek** [comment]
same here. If I run `Fardo` repeatedly, it eventually works.

**Comment by brooth** [comment]
@tmccombs Please, [turn on debug mode](https://github.com/brooth/far.vim/blob/master/doc/far.txt#L692]), reproduce the bug and attach the log file since I have no idea why it fails on your side.

**Comment by tek** [comment]
https://gist.github.com/c5f6c1ef592344583d5d1dc5f5d91640

**Comment by tmccombs** [comment]
I just updated Far and it seems to work now.

**Comment by tmccombs** [comment]
nvm. It still happens. I think what is happenign is it opens a preview buffer when you move the cursor over one of the lines that will be replaced. So if I scroll through all the replacements, it works. But if I do a `:Fardo` immediately it fails, because the buffers haven't been opened yet. Here are the results of debug mode:


[far.vim.log.txt](https://github.com/brooth/far.vim/files/1006660/far.vim.log.txt)

**Comment by brooth** [comment]
Everything works fine on my side, it is really weird. Can you attach your `vim.rc`, `/home/thayne/sandbox/test` dir. any other information you'd think is useful.

**Comment by tmccombs** [comment]
Attached is the sandbox/test directory. the `test.vim` file in it is a minimal vim.rc that I can reproduce the problem with.

[test.zip](https://github.com/brooth/far.vim/files/1009638/test.zip)

**Comment by brooth** [comment]
@tmccombs It should be OK now. Please check. And thanks for the help!

**Comment by tmccombs** [comment]
Looks good. Thanks!
