### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by fleetww** [brooth/far.vim#20]
As far as I can tell there is no way to have the pattern matching be case sensitive, which is pretty useful I think.

**Comment by brooth** [comment]
If you use the default source (which is vimgrep) then it works according `ignorecase` setting. nevertheless, you can use \c and \C to change the behavior.

To match the case for 'foo':
```
:F \Cfoo *.*
```

and to ignore:
```
:F \cfoo *.*
```

here are the details: http://vimdoc.sourceforge.net/htmldoc/quickfix.html#:vimgrep

**Comment by fleetww** [comment]
Thanks! I thought that I was missing something.
