### ISSUE TITLE
How to replace only one instance in the result window instead of running :Fardo that replace all of them?

### ISSUE THREAD

**Issue by pencilcheck** [brooth/far.vim#22]

**Comment by pencilcheck** [comment]
Nvm, I think I found the key binding in the help file, it would be nice if README clarifies that instead of show that implicitly in the gif. It makes it worse that it doesn't even show the key presses.

**Comment by brooth** [comment]
You can exclude all of them with `Shift+X`, select the one you need, than run `:Fardo`
