### ISSUE TITLE
[Feature] Shortcut for closing Far buffer 

### ISSUE THREAD

**Issue by wikimatze** [brooth/far.vim#23]
Plugins like [vimagit](https://github.com/jreybert/vimagit) or [fugitive](http://github.com/tpope/vim-fugitive) provide a mapping like `q` to close the buffer. Would it possible to add such a mapping?

**Comment by brooth** [comment]
which exactly buffer to close? FAR or the one under cursor?

**Comment by brooth** [comment]
I'm closing this since I don't think it's a good idea to rebind default mappings such as `q` in favor to close a buffer. `q` is for recording the macros.

**Comment by wikimatze** [comment]
Okay!
