### ISSUE TITLE
E700: Unknown function: s:ack_expand_curfile

### ISSUE THREAD

**Issue by pwntester** [brooth/far.vim#25]
Getting `E700: Unknown function: s:ack_expand_curfile` when setting the source to `acknvim`

The whole error is:

```
Error detected while processing function Find[18]..far#find[36]..<SNR>75_assemble_context:
line   28:
E700: Unknown function: s:ack_expand_curfile
E117: Unknown function: 0
```

I can see this is the function defined at https://github.com/brooth/far.vim/blob/master/autoload/far.vim#L92
but cannot find where it is declared.

Thanks,
A

**Comment by brooth** [comment]
Fixed. Note that regexp is used for file path matching (instead of wildcards). i.e. to search through python files it'd be:
```
Far number num \.py --source=acknvim 
```

or any files:
```
Far number num . --source=acknvim 
```

**Comment by pwntester** [comment]
Thanks!
