### ISSUE TITLE
Add a header in the listing window with popular mappings

### ISSUE THREAD

**Issue by teto** [brooth/far.vim#26]
I don't use Far very often but when I need it's the perfect tool. The problem is I have a goldfish memory and so I need to look at the help everytime I use it (even with the mnemonics 'x'/'i' (Include/eXclude)). I wonder if it would be possible to have a reminder before the matches for instance:
`Use the 't' mapping to toggle replacement`. It could be optional for people who don't like losing screenspace.

**Comment by brooth** [comment]
I'd recommend you bind `F1` to the appropriate help section for every plugin/filetype/etc you need. For vim it'd be:

```vim
:au FileType far_vim map <buffer><silent><F1> :h far-mappings<cr>   
```

**Comment by teto** [comment]
nice idea thanks
