### ISSUE TITLE
when Fardo => error endif

### ISSUE THREAD

**Issue by tofulm** [brooth/far.vim#27]
Hi,
with neovim 0.2.1
when I try : 
`Far h2 h1 **/*.html`
then
`Fardo`

I'm an error : 
> Line 66 
> e171 endif missing

Thanks for this plugin

**Comment by brooth** [comment]
Sorry for the delay.. Please, enable [debug mode](https://github.com/brooth/far.vim/blob/master/doc/far.txt#L692%5D) and attach log file.

**Comment by tofulm** [comment]
close with bdea0fa
