### ISSUE TITLE
ImportError: No module named 'neovim' when I use ag as far's source

### ISSUE THREAD

**Issue by acgtyrant** [brooth/far.vim#28]
See my [config](https://github.com/acgtyrant/dotfiles/blob/master/Vim/.vimrc#L93-L95).

When I write `let g:far#source = 'ag'` in .vimrc and run Far command in vim, it complains:

```
Error detected while processing function Far[17]..far#find[36]..<SNR>128_assemble_context[40]..far#executors#py3#execute[8]..far#rpc#invoke:
line    9:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 2, in far_rpc_invoker
  File "/home/acgtyrant/dotfiles/Vim/.vim/bundle/far.vim/rplugin/python3/far/__init__.py", line 8, in <module>
    import neovim
ImportError: No module named 'neovim'
E858: Eval did not return a valid python object
Press ENTER or type command to continue
```

I do not know why does it want to import neovim while I use ag.

**Comment by dread-uo** [comment]
It looks like you didn't install the `neovim` python module. You can install it by running
```bash
pip install neovim
```
Can you run `:CheckHealth` on neovim, just for sure?

**Comment by acgtyrant** [comment]
I do not think ag depend on neovim.

**Comment by dread-uo** [comment]
Sorry, I read that again and realized that :p 
I deleted the comment, but you were faster in reading it.

**Comment by dread-uo** [comment]
Does it work if you remove that line from your config and pass `--source=ag` on your map?

**Comment by acgtyrant** [comment]
No, I tried other source which include `vimgrep`, they do not work too.

**Comment by lundberg** [comment]
Try `pip3 install neovim`

**Comment by brooth** [comment]
Sorry for the delay.. It seems that @lundberg  is right. `neovim` module is missing.

**Comment by acgtyrant** [comment]
This is the part of the help:

> *g:far#source*
>     Specify the source. Far source controls candidates gathering.
>     Far.vim provides next sources out of the box:
> 
>         'vimgrep'
>             Synchronous source. Uses |:vimgrep| to find candidates.
>             Does't need external dependencies.
>             Supports multiline search.
> 
>         'ag'
>             Synchronous source. Uses "Ag" (The Silver Searcher) to find candidates.
>             Requires 'ag' installation.
>             Note: Doesn't support multiline search.
> 
>         'agnvim'
>             Asynchronous source. Same as 'ag' but uses Neovim asynchronous API
>             to search candidates in a separate thread.
>             Requires 'nvim' and 'ag' installation.

I use `ag`, it should not require `neovim` module while it is not `agnvim`.

**Comment by brooth** [comment]
You're right, it's a bug. Fixed. Thanks!
