### ISSUE TITLE
Farundo fails to undo

### ISSUE THREAD

**Issue by jdsutherland** [brooth/far.vim#30]
[far.vim.log](https://gist.github.com/3af31a34275bd9783c5bf07e034dcb0f). I think an [asciinema](https://asciinema.org/a/d4IGTtdCsCrnSSUtfO1YmE1fi) best demonstrates the issue.

As I understand it, `:Farundo` is meant to be run in a FAR buffer after doing a `:Fardo` replacement. I've had few cases where `:Farundo` has worked but I've had far more situations where it fails to do anything. Let me know if any of this is unclear.

**Comment by brooth** [comment]
You need to either pass `--auto-write-bufs` arg to `Farundo` or setup `g:far#auto_write_undo_buffers = 1` in your vim.rc. 

Check out the doc section [here](https://github.com/brooth/far.vim/blob/master/doc/far.txt#L668)

**Comment by jdsutherland** [comment]
`:Farundo` fails to undo when `g:far#auto_write_undo_buffers = 1`. It seems that either there is a problem or the docs are unclear.

https://gist.github.com/0479a77d0b3b0ae845b94e7faa20bc65

**Comment by brooth** [comment]
It seems that `undo` command has some changes in API. I can't get it work now. Let's postpone it for now, may be it's a bug on neovim side or I'll have more free time to figure the problem out.

**Comment by izelnakri** [comment]
I'm having the same bug. Undo doesnt work tried with the arguments as well.

**Comment by brooth** [comment]
Sorry for my very long reply. Unfortunately, `Farundo` is a very troubled command while not very useful IMO. So I mentioned it in the help and probably remove next time.
