### ISSUE TITLE
Broked highlight with Far and agnvim source

### ISSUE THREAD

**Issue by bfgasparin** [brooth/far.vim#31]
When using Far with Ag and Neovim asyncronously, it  seems Neovim  API returns the result with scape caracteres for special caracteres, broking the highlight feature on Far.

For example:

Imagine we heave a buffer with the following content:

```php
use Some\Foo\Bar;
```

When we use the command
```
:Far Bar Replated %
 ```

The Far buffer shows the following line:
```
use Some\\Foo\\Bar;  ->        use Some\\FooReplacedar;
```
instead of 
```
use Some\Foo\Bar;    ->        use Some\Foo\Replaced;
```

broking the  highlight feature at  `Bar` word.

(It does not happen when using `ag` syncronous source)

When run Fardo, the replacement runs Ok, The issue is only on Far buffer with `agnvim` source.

My question is: it an issue or a missing configuration of mine?

**Comment by brooth** [comment]
Sorry for my long reply. 
Yeah, it looks like some Neovim Async API encoding logic escapes `\` symbol.
Fixed, thanks!
