### ISSUE TITLE
Neovim / Far prevents other plugins to load

### ISSUE THREAD

**Issue by c0r73x** [brooth/far.vim#32]
Hi, after running `UpdateRemotePlugins` i got a strange problem. All plugins loaded after far will fail with `no notification handler registered`.

But after moving this to the bottom of the ~/.local/share/nvim/rplugin.vim file it works as expected.
```viml
call remote#host#RegisterPlugin('python3', '/home/uscpe/dotfiles/vim/.vim/bundle/far.vim/rplugin/python3/far', [
      \ {'sync': v:false, 'name': '_far_nvim_rpc_async_invoke', 'opts': {}, 'type': 'function'},
     \ ])
```

Here is a screenshot of the errors when placing far at the top of the rplugin.vim file https://goo.gl/m4cjr9

**Comment by brooth** [comment]
Hi! Sorry for my late reply.
Can you attach minimal vim.rc to reproduce this on my side.
Thanks!

**Comment by c0r73x** [comment]
I dont have the problem anymore because I removed the LanguageClient plugin, but something with that plugin and far.vim conflicts, not sure why though.

**Comment by brooth** [comment]
Ok, thanks!
