### ISSUE TITLE
How can I use REGEX to filename?

### ISSUE THREAD

**Issue by cancue** [brooth/far.vim#33]
Is there any way to use regex on filename?

ex)
:F far (app|test)/**/*.(?!log)

**Comment by brooth** [comment]
Sorry for my long reply.

If you use default source (`vimgrep`) you can use wildcards for file names only. `ag` and `ack` use regexp.

`:F far (app|test)/**/*.(?!log) --source=ag`

Go to `:help g:far#source` for details.
