### ISSUE TITLE
Exclude directories

### ISSUE THREAD

**Issue by sitilge** [brooth/far.vim#34]
Is it possible to exclude unwanted directories? E.g. I'm using `php` and `vendor` is usually not the dir you want to include in the search.

**Comment by brooth** [comment]
Sorry for my long reply.
If you use default source (`vimgrep`) than you can exclude any dirs using wildignore:
vim.rc:
```
set wildignore+=*/vendor/*
```

**Comment by sitilge** [comment]
Any eay to exclude dirs/files per search?

**Comment by brooth** [comment]
No if you use default source. Yes if it's `ag` or `ack`:
`:Far Search Replace . --source=ag --ignore-name vendor`

`man ag` for details
