### ISSUE TITLE
error Far with source = agnvim

### ISSUE THREAD

**Issue by tofulm** [brooth/far.vim#36]
when I run the command : 
`:far CONFIG[p_ MA_CONFIG{p_ .html`
I've an error
[far.vim.log.txt](https://github.com/brooth/far.vim/files/1322437/far.vim.log.txt)

**Comment by brooth** [comment]
Sorry for my long reply!
You need to escape `[` symbol as `\[` since `pattern` is a regexp.
I need to handle this error and show appropriate error message though. 
Thanks!

**Comment by tofulm** [comment]
thanks
