### ISSUE TITLE
Enhacement request: Opening file in original window

### ISSUE THREAD

**Issue by pwntester** [brooth/far.vim#37]
Great plugin thanks!

I have a suggestion though, would it be possible to add a configuration setting so when using far-jump on a non-opened buffer, it would be opened in the original window (the one active when the Far command was called). The idea is to be able to open one of the matching source files and keep the Far buffer showing in the Far window.

Thanks

**Comment by brooth** [comment]
Hi, thanks! 
Sorry for my late reply. It might be useful I guess, but currently I have no time to implement it. PR is welcome though.
