### ISSUE TITLE
Far freezes neoVim

### ISSUE THREAD

**Issue by bannier** [brooth/far.vim#38]
with Far beta2 on neovim 0.1.7 on a directory with +30K files
Any Far command like`Far SEARCH REPLACE src/**` freezes neovim.

It works fine on other directories

Also tried with :
- neovim 2.1 
- far.vim with 'commit': 3376dc592871c4f1407591d13708c27f29d6ad73

(It used to work fine)

(otherwise Far is really great)

**Comment by bannier** [comment]
This seems related to the specific directory I'm working on as it works on other directories

**Comment by brooth** [comment]
Sorry for my late reply. What source do you use? By default it's `vimgrep` that works pretty slow. You can test its speed by internal vim command `:vimgrep /SEARCH/g src/**`. Consider to use different source, e.g. `agnvim`, it uses `ag` (the silver searcher) and neovim async api.  
Go to `:help g:far#source` for details.

**Comment by jacky1193610322** [comment]
but ag requires python3, in my environment, other plugin needs python2, vim can't use two different version at the same time,so I must use vimgrep.

**Comment by brooth** [comment]
there is nothing I can do about. `Far` doesn't search by itself. It uses other tools for this. If `vimgrep` is slow then `Far` is slow as well.

**Comment by jacky1193610322** [comment]
no, I mean, if Far use ag, it requires python3. I hope Far can support python2

**Comment by brooth** [comment]
what about `ack` or `ripgrep` (here how you can set it up https://github.com/brooth/far.vim/pull/4)?

**Comment by jacky1193610322** [comment]
It works, Thank you, but Far is also slow, I use rg search in the terminal, it's very fast, but when I use Far to replace something, search the same thing in the same directory, it's also slow, but faster than before, and when I use up and down to preview the match, it  freezes vim a little.

**Comment by jacky1193610322** [comment]
rg source is not support in the branch master now, how to config the vim

**Comment by brooth** [comment]
Well, sorry, I looked closer and Far requires python3 for all sources, but vimgrep.

**Comment by jacky1193610322** [comment]
Thank you, can you support python2?

**Comment by brooth** [comment]
Sorry, have no time. PR is welcome though.

**Comment by jacky1193610322** [comment]
OK, Thank you very much

**Comment by bannier** [comment]
Using `agnvim` as source fixes the issue thanks !
