### ISSUE TITLE
failed to execute source. unknown error

### ISSUE THREAD

**Issue by tofulm** [brooth/far.vim#39]
Hello,
with : 
- neovim 0.2.2
- last far.vim
- let g:far#source='agnvim'

I've an error : **failed to execute source. unknown error**

[far.vim.log](https://github.com/brooth/far.vim/files/1466475/far.vim.log)

Thanks for everything

**Comment by brooth** [comment]
Have you got `ag` installed system wide?

**Comment by tofulm** [comment]
yes

**Comment by tofulm** [comment]
if :  `:F inscriptions .html`
error : error caught in async handler
log : [far.vim.log](https://github.com/brooth/far.vim/files/1466577/far.vim.log)

and 
if :  `:F inner .html`
error : failed to execute source. unknown error
log : [far.vim.log](https://github.com/brooth/far.vim/files/1466580/far.vim.log)

**Comment by brooth** [comment]
Some changes in neovim async api broke the source. Fixed. Thanks!

**Comment by tofulm** [comment]
it's ok !
thanks !!
