### ISSUE TITLE
Make filemask parameter optional

### ISSUE THREAD

**Issue by b-ggs** [brooth/far.vim#41]
For every project-wide search, you always have to provide a filemask.

For example, to search for `query` in all files, it's `:F query .`

Can the default value for the filemask be `.`, even only for `:F` and not the find-and-replace methods?

It would be easier to key in `:F query` like most other project-wide search vim plugins.

**Comment by brooth** [comment]
Implemented. Use `g:far#default_file_mask` variable to control default file-mask, otherwise it is `%` (current file).
