### ISSUE TITLE
Add `ripgrep` support?

### ISSUE THREAD

**Issue by ErichDonGubler** [brooth/far.vim#43]
`ripgrep` is slowly becoming one of my favorite *nix tools, but this plugin doesn't quite support it yet! Would it be possible to add this? I'd be more than happy to do it with some mentoring. :)

It looks like [this comment](https://github.com/brooth/far.vim/issues/38#issuecomment-344942628) has a good lead on a configuration that would work with `rg`.

**Comment by brooth** [comment]
Merged https://github.com/brooth/far.vim/pull/46
