### ISSUE TITLE
unable to handle parenthesis ?

### ISSUE THREAD

**Issue by bannier** [brooth/far.vim#45]
if I do something like this : 

```
Far someFunction\(someParam\) TEST .*
```

Far will correctly list all occurence but then when I run `:Fardo` nothing happens : 

![image](https://user-images.githubusercontent.com/649149/39197343-868f1abe-47e4-11e8-8952-04c28e7fcb15.png)

looks like there was errors on every lines but I don't have details

Works fine if I use it without parenthesis

**Comment by brooth** [comment]
Works on my side. Please attach the logs next time and I'll reopen the issue
