### ISSUE TITLE
Undocumented file-mask difference between vimgrep and ag (i.e. glob vs regex)

### ISSUE THREAD

**Issue by bedax** [brooth/far.vim#48]
As far as I can tell, where vimgrep uses the glob syntax for the file-mask, ag uses regex patterns. So where I was using `**/*.html`, now I have to use `.*/*.html`. And depending on which regex parser the user is used to, they may think they need `.*\/.*\.html`, which is not as convenient.

So while I prefer the glob syntax, I don't think Ag supports it. This may one more reason to support ripgrep as mentioned in #43.

Either way, I think this difference should be documented.

Regardless, thank you for this excellent plugin.

**Comment by brooth** [comment]
Added appropriate info in the help. Thanks!
