### ISSUE TITLE
Change Filetype For ftplugin

### ISSUE THREAD

**Issue by weilbith** [brooth/far.vim#50]
Hello!
I like to create a filetype plugin to define special mappings for the far buffer like executing `Fardo`.
Unfortunately is the filetype `far_vim` and the ftplugin convention does not allow an underscore, cause that is used to separate ftplugins.
It would be awesome if the filetype could be renamed to simple 'far' for example.
Thanks for reading!

**Comment by brooth** [comment]
Sorry for my late reply. Syntax renamed to "far"
