### ISSUE TITLE
Undefined variable: signs

### ISSUE THREAD

**Issue by argoyal** [brooth/far.vim#53]
I keep getting this error when I do 'Fardo': E121: Undefined variable: signs

The stuff that actually happens is it replaces the first file but then it does not go to the next replacement. Any fix?

As per logs the error arises when it starts to replace a particular line then it quits by saying no far bufs

```
[14:24:53] ============= FAR DO ================
[14:24:53] far#replace([])
[14:24:53] replines:0
[14:24:53] replacing buffer <file_name>
[14:24:53] bufdo: 22s/\%24c<Find Text>/<Replace Text>/e#|write
[14:24:55] no far bufs, stopping resize timer #5
```

**Comment by brooth** [comment]
Could you attach a basic `vim.rc` and a test directory+files so I could reproduce it on my side. Unfortunately, I cannot do that based on the provided info. I'll reopen the issue then

**Comment by argoyal** [comment]
I got this issue resolved. If I guess, the problem would be with my Python installations on Mac. A lot of problems were arising in my Vim because of stale Python installations. I had to uninstall a couple of unused versions which were referenced in a couple of places. This problem probably caused a broken installation of Vim as well. On following these cleanup processes and reinstalling Vim, I got everything working. Sorry for the trouble.
