### ISSUE TITLE
Highlight performance

### ISSUE THREAD

**Issue by paulondc** [brooth/far.vim#55]
Hi,

When the option `g:far#highlight_match` is enabled (default) the performance degrades drastically during the scrolling of the results to a point that becomes unusable. By disabling that option the scrolling becomes instantaneous.

I've recorded a video about it:
https://www.youtube.com/watch?v=dmKQLMMbu3I

Following below info about the video:
- Software: `nvim 0.2.2`
- System: `ubuntu 16.04`
- Hardware: `i7-6700 / 12GB RAM`
- Source code used for the video:  `https://github.com/meboHQ/mebo`
- Far searching syntax: `Far Input Foo  src/**/*.js`

Let me know if you need any extra information.

**Comment by brooth** [comment]
Well, this is why I added this option (g:far#highlight_match) - to be able to turn the highlight off if a lot of results expected. I struggled with the performance quite a while and this was my best. Seems like vim (nvim) has its issues with syntax highlighting in the first place so there no that much I can do here. 

If there is a guru in the area, PR is welcomed.

**Comment by MichaelOstermann** [comment]
Scrolling performance for me was still very bad after the suggestions from https://github.com/brooth/far.vim/pull/59

Doing `setlocal nocursorline` is what made it buttersmooth for me!

**Comment by paulondc** [comment]
Hi @MichaelOstermann, 

Would you mind to share more details about your environment and the code-base you were having performance issues ?

Cheers,
Paulo
