### ISSUE TITLE
ripgrip stopped working.

### ISSUE THREAD

**Issue by carlitux** [brooth/far.vim#58]
How should be used with glob? getting error `source error: unrecognized file type: **/*.html\n`

**Comment by brooth** [comment]
Check out this issue - https://github.com/brooth/far.vim/issues/49
And ripgrep doc - https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs.
Also, make sure `rg` source configuration is not overwritten in your `vim.rc`

**Comment by carlitux** [comment]
thank you, looks like cached source were working instead the new one, working!
