### ISSUE TITLE
Invalid Pattern: bad escape

### ISSUE THREAD

**Issue by Nomad145** [brooth/far.vim#60]
First off, this plugin is easily one of my favorites.  Thanks for all the work you've put into it, @brooth.  It is essential to my daily workflow.

I noticed today that this pattern is starting to return an error:
```
:Far App\\Controller\\FooController App\\Controller\\BarController \.php --source=ag
source error: invalid pattern: bad escape \C at position 3
```

It looks like the behavior changed in d3d3abcc, as I can checkout 5f8016e1 and it works as I expect.  I haven't dug into it any further than that, but let me know how I can help further.  I looked through the updated help files for `far`, and as best as I can tell I'm still escaping correctly.

Thanks again!

**Comment by brooth** [comment]
> First off, this plugin is easily one of my favorites. Thanks for all the work you've put into it, @brooth. It is essential to my daily workflow.

Hey, thanks!

I'm not sure how it worked earlier but to escape ` \` you need use `\\\\` - first for vim, second for the source (ag). Try to run this command:

`:Far App\\\\Controller\\\\FooController App\\\\Controller\\\\BarController \.php --source=ag`

and if no luck then please attach your far.vim.log file (how-to in the help)

**Comment by Nomad145** [comment]
That does the trick!  Thanks!  I tested `\\\\` with a few use cases (once with `ag` as the source and once with `%` as the file mask and no source) and both worked appropriately.

I opened #61 in case this came up again.  Let me know what you think!

**Comment by brooth** [comment]
Glad it does! Thanks for the PR
