### ISSUE TITLE
Escaping spaces doesn't seem to work

### ISSUE THREAD

**Issue by FuzzOli87** [brooth/far.vim#63]
Hello,

This might just be my own ignorance but I've tried everything under the sun to search and replace with a sentence. I've tried

```
:F func\ main ./**
```

And it doesn't return a single hit although there are certainly some there.

**Comment by Jefferson-Faseler** [comment]
I'm having the same issue, I'm tried `\s` like in the help, but no dice.

**Comment by tvatter** [comment]
Same here with neovim.

**Comment by ApolloTang** [comment]
@Jefferson-Faseler work if you use `\\s` (need to escape backslash)

**Comment by tvatter** [comment]
Lol, yes, obviously, thanks and sorry!

**Comment by brooth** [comment]
Sorry to all for my late reply, fixed here #62, just use `\ ` from now on.
