### ISSUE TITLE
--source=rg not working with volt on windows

### ISSUE THREAD

**Issue by hulucc** [brooth/far.vim#65]
![image](https://user-images.githubusercontent.com/4343900/54913115-0b1bba80-4f2d-11e9-93dd-3aaba970ed53.png)

Something wrong about the path escape.
I can make it work by manually execute:
```
py3 import sys
py3 sys.path.append("c:\\Users\\hulucc\\vimfiles\\pack\\volt\\opt\\github.com_brooth_far.vim\\rplugin\\python3")
```

**Comment by hulucc** [comment]
I created a fix which works for me. please check

**Comment by brooth** [comment]
Merged. Thanks!
