### ISSUE TITLE
g:far#source = 'rg'; but ripgrep does not respect .gitignore ? 

### ISSUE THREAD

**Issue by ApolloTang** [brooth/far.vim#69]
From my understanding reading documentation, I can enable ripgrep with:
```
let g:far#source = 'rg'
```
in my .vimrc.

(previous instruction in https://github.com/brooth/far.vim/pull/4#issuecomment-268449751 is no longer needed)

But how do I get search engine (repgrep) to respect .gitignore?  With `g:far#source = 'rg'` it no longer respecting wildignore and is searching into node_modules/ folder.

How do I confirm that  ripgrep is actually the current search engine ?

Thanks, 

... love your plugin!!

**Comment by ApolloTang** [comment]
just wanna add:
in terminal ripgrep is respected .gitignore (and does not search into node_modules, for example)  but this behaviour is not working for ripgrep in Far.

**Comment by ApolloTang** [comment]
nvm, I just read 
https://github.com/brooth/far.vim/issues/58
#49 Ripgrep file mask changed to --glob mode

so instead of 
```
:F hello **/*
```
now is:
```
:F hello **/*.*
```

**Comment by hbarcelos** [comment]
I'm having the same problem.

I read this, but I'm not sure what the "solution" is. Can someone help me?

All I have in my `.vimrc` is:
```
let g:far#source = 'rg'
```

However, gitignored results keep showing up.

Do I need to have an explicit `farignore` file to make this work?

**Comment by dylan-chong** [comment]
> Do I need to have an explicit farignore file to make this work?

Yes :(

I have made a hack to work around it
https://github.com/brooth/far.vim/issues/91#issuecomment-817377313
