### ISSUE TITLE
Duplicate entries for multiple single line matches when using F

### ISSUE THREAD

**Issue by amsayk** [brooth/far.vim#7]
commands: 

:F  Center **/*.js

Output:
<img width="713" alt="screenshot 2016-12-21 22 58 52" src="https://cloud.githubusercontent.com/assets/271111/21409445/35ffbc18-c7d2-11e6-939e-a8de92209b0e.png">

Same result with :Far.

**Comment by brooth** [comment]
@amsayk what `source` is this? if it's your [rg](https://github.com/brooth/far.vim/pull/4) one then try to remove `args.fix_cnum = next` line.

**Comment by amsayk** [comment]
Hi,

Yes that did it. I will send you a pr.

Thanks.
