### ISSUE TITLE
`Fardo` for each finding and skip any if we want to

### ISSUE THREAD

**Issue by sameera207** [brooth/far.vim#73]
Hi, thanks a lot for the work on the plugin, it works flawlessly with my Neovim setup. However I have a quick question, 

Is there a way to run `Fardo` for each finding and skip any if we want to? 

Because from my understanding, `Fardo` will replace all the selected matches, I'm thinking about going through each match and replace or skip. 

I've checked README and also `: help Far`, but I couldn't find anything related. I did find an option called `params` which you can pass but was unable to find an example on that

cheers

**Comment by AlexVKO** [comment]
you can **Toggle** the match by placing the cursor above it and presst **t**

**Comment by jaydorsey** [comment]
As someone who doesn't often make it far into the vim help files, these would both be excellent additions to the README. I'll attempt a PR later unless someone beats me to it

**Comment by sameera207** [comment]
hey @roosemberth and @AlexVKO, thanks for the tip.  `x` and `i` works a treat. closing the issue :)
