### ISSUE TITLE
Unknown function: far#tools#isdebug error

### ISSUE THREAD

**Issue by yanlobkarev** [brooth/far.vim#8]
Hi, I'm running command `:Far foofoofoo barbarbar .*\.py` and nvim spits out following error message:
```
no notification handler registered for "/Users/andCo/.vim/plugged/far.vim/rplugin/python3/far:function:_far_nvim_rpc_async_invoke"
Encountered NvimError loading plugin at /Users/andCo/.vim/plugged/far.vim/rplugin/python3/far: b'Vim:E117: Unknown function: far#tools#isdebug'
Traceback (most recent call last):
  File "/Users/andCo/Library/Python/3.5/lib/python/site-packages/neovim/plugin/host.py", line 133, in _load
    self._discover_classes(module, handlers, path)
  File "/Users/andCo/Library/Python/3.5/lib/python/site-packages/neovim/plugin/host.py", line 163, in _discover_classes
    plugin = cls(self._configure_nvim_for(cls))
  File "/Users/andCo/.vim/plugged/far.vim/rplugin/python3/far/__init__.py", line 21, in __init__
    if nvim.eval('far#tools#isdebug()'):
  File "/Users/andCo/Library/Python/3.5/lib/python/site-packages/neovim/api/nvim.py", line 224, in eval
    return self.request('vim_eval', string, **kwargs)
  File "/Users/andCo/Library/Python/3.5/lib/python/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
neovim.api.nvim.NvimError: b'Vim:E117: Unknown function: far#tools#isdebug'
```

I use `nvim 0.1.7`, under `Python 2.7.10`, with latest `far.vim` revision (`e6b298dfd326ff6870c02f4baa4244749d06d0a1`).

That's plugin setup in my `init.vim` at the current moment:
```
Plug 'brooth/far.vim' " Find And Replace
" NB: ag always searches recursively, file mask have to be of a PCRE type
let g:far#file_mask_favorites = ['%', '.*\.py', '.*\.js', '.*']  
let g:far#preview_window_height = 30
let g:far#window_width = 120
let g:far#source='agnvim'
let g:far#debug = 1
```
That's my `far.vim.log` attached:
[far.vim.log.zip](https://github.com/brooth/far.vim/files/669942/far.vim.log.zip)

I believe crash happens here: https://github.com/brooth/far.vim/blob/master/rplugin/python3/far/__init__.py#L21 .

By the way, thanks for the plugin. It's quite awesome))
With best regards,
Yan

**Comment by brooth** [comment]
Hi Yan!
> By the way, thanks for the plugin. It's quite awesome))

Thanks!  :blush: 

I'm not sure why it fails, can you try to update neovim python client and check it again?
```
pip3 install neovim --upgrade
```

**Comment by yanlobkarev** [comment]
Sorry, `pip3 install neovim --upgrade` didn't help.
Have following output after that:
```

**Comment by brooth** [comment]
How about `:UpdateRemotePlugins`, does it help?

**Comment by yanlobkarev** [comment]
@brooth Nope, `:PlugUpdate` didn't help.

**Comment by brooth** [comment]
@yanlobkarev  not `:PlugUpdate` but `:UpdateRemotePlugins' ;)

**Comment by yanlobkarev** [comment]
@brooth 
Oops, sorry. I ran `:UpdateRemotePlugins` and generated `rplugin.vim` of following content:
```" python3 plugins
call remote#host#RegisterPlugin('python3', '/Users/andCo/.config/nvim/rplugin/python3/deoplete', [
      \ {'sync': v:true, 'name': '_deoplete', 'opts': {}, 'type': 'function'},
     \ ])
call remote#host#RegisterPlugin('python3', '/Users/andCo/.vim/plugged/far.vim/rplugin/python3/far', [
      \ {'sync': v:false, 'name': '_far_nvim_rpc_async_invoke', 'opts': {}, 'type': 'function'},
     \ ])

" ruby plugins

" python plugins
```

But also didn't helped.

**Comment by yanlobkarev** [comment]
Sorry, probably we can close issue if it's not reproducible on Your site.
If someone else gonna reproduce it or I figure out what's the case- 
we will reopen issue (or attach useful info)?

**Comment by brooth** [comment]
@yanlobkarev Thanks for help! I guess it might be related to your nvim version. Otherwise no idea, code looks fine. Let's keep it open for awhile. Please, let me know if it'll stop crashing for a reason.

**Comment by yanlobkarev** [comment]
@brooth Ok, will try to reproduce it after nvim update.

**Comment by yanlobkarev** [comment]
Definitely my local setup error. After reinstalling from ground up- everything worked fine.

**Comment by brooth** [comment]
@yanlobkarev Cool, thanks for letting me know!

**Comment by pencilcheck** [comment]
Thanks for the command to upgrade pip3 neovim binding, that fixed the issue where it couldn't find python3 executable. If you can put that into README that would be awesome.
