### ISSUE TITLE
Error: "File in current buffer is not readable"

### ISSUE THREAD

**Issue by camflint** [brooth/far.vim#86]
I get this error whenever I use the '%' file mask to search for a pattern in the current buffer. It happens _every time_ for my .vimrc, but not for other files:

```
File in current buffer is not readable.
Invalid file mask
Press ENTER or type command to continue
```

The buffer is not set to readonly, and I can't figure out why Far would think that the file is unreadable. Anyone have an idea of how to troubleshoot further?

**Comment by dagadbm** [comment]
same problem with basically anything. makes far unusable for my use case
