### ISSUE TITLE
rg file mask - can't gitignore

### ISSUE THREAD

**Issue by dylan-chong** [brooth/far.vim#91]
I am using `let g:far#source = 'rgnvim'`

- `:F hello` only searches the current file (is this expected?)
- `:F hello *` searches all files including git ignored files

according to the logs, this command will run:

`rg --with-filename --no-heading --vimgrep --max-count=something hello *` 

which does not respect git ignore

**Comment by brooth** [comment]
That's right, far.vim doesn't respect git ignore. Feel free to submit an RP if you'd like to have this feature.

**Comment by dylan-chong** [comment]
Have made a temp PR that breaks globbing but follows git ignore. https://github.com/dylan-chong/far.vim/pull/1/files <-- for anyone who wants to use this hack
