### ISSUE TITLE
Is there a way to exclude all matches of a /search in the results after the original search to be done

### ISSUE THREAD

**Issue by dylan-chong** [brooth/far.vim#92]
Say that I perform a `:Far a b`  and I decide I want to exclude all matches  in files with a `.beam` extension.

 one way to do that is to type `/beam<Enter>xnxnxnxnx`...

 is there any other way to do this?

**Comment by brooth** [comment]
Sources such as `ag`, `rgrep` support regex that can help you. Please take your time to google it.

**Comment by dylan-chong** [comment]
@brooth I would like to do this after performing the regular expression search. The problem with trying to add all the search criteria to the regular expression is that I may go through the search results, manually exclude a bunch, then realise that I need to exclude a whole group of different matches ( E.g. matches that have an extension).  in which case, I don't want to have to reperform the search with new criteria, and manually  exclude the same bunch again
