### ISSUE TITLE
Search all files by default?

### ISSUE THREAD

**Issue by LandonSchropp** [brooth/far.vim#99]
With far.vim, I can search all files in my project by typing `:F <term> *`. Is there a way I can make the `*` the default scope, so I only have to type `:F <term>`?

Thanks!

**Comment by benshu** [comment]
You should be able to achieve that with the following configuration:
```    
let g:far#default_file_mask = '*'
```

**Comment by LandonSchropp** [comment]
Awesome! Thank you.
